{% set version = "0.13.0" %}

package:
  name: bloscpack
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bloscpack/bloscpack-{{ version }}.tar.gz
  sha256: a31a24bb3ac60a0de5ba4fffb5aa232dbb3cd97b49dbeea1fcf69561a7ca2d31

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - blpk=bloscpack.cli:main
  skip: True  # [win]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - blosc
    - python-blosc
    - numpy

test:
  imports:
    - bloscpack
  commands:
    - blpk --help

about:
  home: https://github.com/Blosc/bloscpack
  license: Apache 2.0
  summary: 'Command line interface to and serialization format for Blosc'

extra:
  recipe-maintainers:
    - danielfrg
