{% set version = "0.15.0" %}

package:
  name: bloscpack
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bloscpack/bloscpack-{{ version }}.tar.gz
  sha256: 1fd53e5bec6f6fb98051cd324c68e65028bdf5efabab5f4d09b769fd1d8103e1

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - blpk = bloscpack.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - blosc
    - python-blosc
    - numpy

test:
  imports:
    - bloscpack
  commands:
    - blpk --help

about:
  home: https://github.com/Blosc/bloscpack
  license: MIT
  summary: 'Command line interface to and serialization format for Blosc'

extra:
  recipe-maintainers:
    - danielfrg
