{% set version = "0.11.0" %}

package:
  name: bloscpack
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bloscpack/bloscpack-{{ version }}.tar.gz
  sha256: 8c735ca961ca01141f741a23320d2acb7c1191863b26505bc8fc8e53110ac33b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - blpk=bloscpack.cli:main
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - blosc
    - python-blosc
    - numpy

test:
  imports:
    - bloscpack
  commands:
    - blpk --help

about:
  home: https://github.com/Blosc/bloscpack
  license: Apache 2.0
  summary: 'Command line interface to and serialization format for Blosc'

extra:
  recipe-maintainers:
    - danielfrg
