appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eFTv7lfQnywvM3V5QhME5jfxVxbHp1ohhrSETGMIuBzadsOaf0YS8dEY2wZgnor7MbQLSPlhWAZsCTSkPLoXXrsk56uVs6i9SgzdCfWcgLO/FAJe+V+q1Tw9iewZxNREPGSo668uZUrhAwzu3If/z2loM0LJdVwoAeSVuw37ERCvx8FTasiWRcCdlEnSRjZHrO7o9kBEHbketBQ3q8ogjDnnY7rnq+exE4KRD67HODgPP71Q8NG5QsfKLjHEdX89z+ICsIk3Rj7l0zIn8LMHEIp003UbYAaHhtvQtSuBl3th6aHVuhbCr5XExqVPWql+Ko4KPkGceSrlXikyDKiihwOGEHMpKvFInoozDXxp3bc5BBleLgHCvVWOuCLUocHL1ZMSx+BYKsCFsnA0BehRw8d95OLe97s4sItn93MmFzABWB+11oaWobKOzYIdmjOcqBNQCynGI8NMLGkymRnrx4nt+d4h7wmjTvEbw0Lt5W+/InkjGmM4he9zDBcRJQXuDCiiZ7VwIy0Z6+R8gRP/uYWXwEXV2TYY/zLu71pgRehvbe6XPE6roMXKmgdLIFszbYr8p8oVISxSQDj42M/5u/uFUnN7q/SIo+va+y5fiGXs1ClzWrs0Sm+89db3+DUZJ7rUuNbbTqfXz79+SpCtcpkJZgaklNvYlUmCId1scGM=}
conda_forge_output_validation: true
